### ISSUE TITLE
Please contact me for kernel PLEASE !!!!

### ISSUE THREAD

**Issue by sagoktay** [DOITfit/android_kernel_xiaomi#1]
Bro your kernel is amazing one of for K20 pro. Please contact me on telegram https://t.me/AnimaVestraa
Please update because your kernel's touch drivers is awesome but needs optimization a little bit. It has little delay. Just contact me i want to talk with you

**Comment by DOITfit** [comment]
Dude, can you tell me what system you're using

**Comment by DOITfit** [comment]
Dude, can you tell me what system you're using

**Comment by sagoktay** [comment]
Raphael, Miui bro, also it works on aosp. Contact me on telegram broo

14 Nis 2021 Çar 14:12 tarihinde DOITfit ***@***.***> şunu
yazdı:

**Comment by sagoktay** [comment]
We should talk bro gmail is slowly communication. +905442216286 please
write on wp

14 Nis 2021 Çar 14:16 tarihinde ACEHZI ***@***.***> şunu yazdı:

**Comment by sagoktay** [comment]
Waiting for you bro comeback please. You must update this best kernel

**Comment by DOITfit** [comment]
This is my Telegram https://t.me/Doitfir
